const API = import.meta.env.VITE_API_URL ?? '';

export default function AIReport({ report, invId, name }: { report: string | null; invId: string; name: string }) {
  if (!report) {
    return (
      <div className="text-center py-20 text-zinc-600">
        <div className="text-5xl mb-3">🤖</div>
        <div className="text-lg font-medium text-zinc-500">AI Report Not Ready</div>
        <div className="text-sm mt-1">The AI analyst runs after all modules complete</div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="text-xs text-zinc-500">Generated by Claude Sonnet — Executive-grade security analysis</div>
        <a
          href={`${API}/api/investigations/${invId}/report?format=md`}
          download
          className="text-xs bg-zinc-800 hover:bg-zinc-700 text-zinc-300 px-3 py-1.5 rounded border border-zinc-700 transition-colors"
        >
          ↓ Download .md
        </a>
      </div>

      <div
        className="bg-zinc-900 border border-zinc-800 rounded-lg p-6 prose prose-invert prose-sm max-w-none
          [&_h1]:text-xl [&_h1]:font-bold [&_h1]:text-white [&_h1]:mb-4
          [&_h2]:text-base [&_h2]:font-semibold [&_h2]:text-zinc-200 [&_h2]:mt-6 [&_h2]:mb-2 [&_h2]:border-b [&_h2]:border-zinc-700 [&_h2]:pb-1
          [&_h3]:text-sm [&_h3]:font-semibold [&_h3]:text-zinc-300 [&_h3]:mt-4 [&_h3]:mb-1
          [&_p]:text-zinc-300 [&_p]:leading-relaxed [&_p]:mb-3
          [&_ul]:space-y-1 [&_li]:text-zinc-300 [&_li]:text-sm
          [&_strong]:text-white
          [&_code]:bg-zinc-800 [&_code]:text-green-400 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-xs
          [&_pre]:bg-zinc-950 [&_pre]:border [&_pre]:border-zinc-800 [&_pre]:rounded [&_pre]:p-3 [&_pre]:overflow-x-auto"
      >
        <ReportMarkdown content={report} />
      </div>
    </div>
  );
}

function ReportMarkdown({ content }: { content: string }) {
  const lines = content.split('\n');
  const elements: React.ReactNode[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (line.startsWith('### ')) {
      elements.push(<h3 key={i}>{line.slice(4)}</h3>);
    } else if (line.startsWith('## ')) {
      elements.push(<h2 key={i}>{line.slice(3)}</h2>);
    } else if (line.startsWith('# ')) {
      elements.push(<h1 key={i}>{line.slice(2)}</h1>);
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      const items: string[] = [];
      while (i < lines.length && (lines[i].startsWith('- ') || lines[i].startsWith('* '))) {
        items.push(lines[i].slice(2));
        i++;
      }
      elements.push(
        <ul key={`ul-${i}`} className="list-disc list-inside space-y-1 my-2">
          {items.map((it, j) => <li key={j} dangerouslySetInnerHTML={{ __html: inlineFormat(it) }} />)}
        </ul>
      );
      continue;
    } else if (line.startsWith('```')) {
      const lang = line.slice(3);
      const codeLines: string[] = [];
      i++;
      while (i < lines.length && !lines[i].startsWith('```')) {
        codeLines.push(lines[i]);
        i++;
      }
      elements.push(
        <pre key={`pre-${i}`} className="bg-zinc-950 border border-zinc-800 rounded p-3 overflow-x-auto my-3">
          <code className="text-green-400 text-xs">{codeLines.join('\n')}</code>
        </pre>
      );
    } else if (line.trim() === '') {
      // skip blank
    } else {
      elements.push(
        <p key={i} dangerouslySetInnerHTML={{ __html: inlineFormat(line) }} />
      );
    }
    i++;
  }

  return <>{elements}</>;
}

function inlineFormat(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code class="bg-zinc-800 text-green-400 px-1 py-0.5 rounded text-xs">$1</code>');
}
