server {
    listen 80;
    location /apexred {
        alias /usr/share/nginx/html/apexred;
        try_files $uri $uri/ /apexred/index.html;
    }
    location /apexred/api {
        proxy_pass http://apex-red-api:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
    }
}
